// 业务常量（与前端 mp/src/utils/constants.ts 对齐）

const ROLE = {
  ROLE_SALES: "ROLE_SALES",
  ROLE_CHANNEL: "ROLE_CHANNEL",
  ROLE_ADMIN: "ROLE_ADMIN",
};

const CUSTOMER_SOURCE = {
  SELF_VISIT: "SELF_VISIT",
  SELF_DEVELOP: "SELF_DEVELOP",
  CHANNEL_COMPANY: "CHANNEL_COMPANY",
  PERSONAL_REFERRAL: "PERSONAL_REFERRAL",
};

const INTENT_LEVEL = {
  HIGH: "HIGH",
  MEDIUM: "MEDIUM",
  LOW: "LOW",
  NONE: "NONE",
};

const CUSTOMER_STATUS = {
  ACTIVE: "ACTIVE",
  DEAL: "DEAL",
  PUBLIC_POOL: "PUBLIC_POOL",
  EXPIRED: "EXPIRED",
  UNVISITED: "UNVISITED",
};

const FOLLOWUP_METHOD = {
  PHONE: "PHONE",
  WECHAT: "WECHAT",
  FACE: "FACE",
};

// 审计日志动作
const AUDIT_ACTION = {
  CUSTOMER_CREATE: "CUSTOMER_CREATE",
  CUSTOMER_UPDATE: "CUSTOMER_UPDATE",
  CUSTOMER_INTENT_CHANGE: "CUSTOMER_INTENT_CHANGE",
  CUSTOMER_ASSIGN: "CUSTOMER_ASSIGN",
  MOVE_PUBLIC: "MOVE_PUBLIC",
  CLAIM_PUBLIC: "CLAIM_PUBLIC",
  CLAIM_UNVISITED: "CLAIM_UNVISITED",
  APPROVE: "APPROVE",
  CHANNEL_ARRIVE: "CHANNEL_ARRIVE",
  CHANNEL_RE_REPORT: "CHANNEL_RE_REPORT",
  CHANNEL_EXPIRE: "CHANNEL_EXPIRE",
  FOLLOWUP_CREATE: "FOLLOWUP_CREATE",
  EXPORT: "EXPORT",
  USER_RESET_PASSWORD: "USER_RESET_PASSWORD",
  USER_CREATE: "USER_CREATE",
  USER_UPDATE: "USER_UPDATE",
  PROJECT_CREATE: "PROJECT_CREATE",
  PROJECT_UPDATE: "PROJECT_UPDATE",
  COMPANY_CREATE: "COMPANY_CREATE",
  COMPANY_UPDATE: "COMPANY_UPDATE",
  CONFIG_UPDATE: "CONFIG_UPDATE",
};

// TransferLog 动作
const TRANSFER_ACTION = {
  ASSIGN: "ASSIGN",
  MOVE_PUBLIC: "MOVE_PUBLIC",
  CLAIM: "CLAIM",
  EXPIRE: "EXPIRE",
  RE_REPORT: "RE_REPORT",
  APPROVE: "APPROVE",
  ARRIVE: "ARRIVE",
  CONFLICT_APPROVED: "CONFLICT_APPROVED",
};

module.exports = {
  ROLE,
  CUSTOMER_SOURCE,
  INTENT_LEVEL,
  CUSTOMER_STATUS,
  FOLLOWUP_METHOD,
  AUDIT_ACTION,
  TRANSFER_ACTION,
};
